[build]
  # No build command needed for static sites
  publish = "."
  
[build.environment]
  # Skip npm install since we don't need it for static HTML
  NPM_FLAGS = "--ignore-scripts"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 